import { i } from "framer-motion/client";

export const topBarData = [
  {
    // apply translation in UI components; store a plain string or key here
    first: "banner.hello",
    second: "banner.iam",
    third: "banner.firstName",
    fourth: "banner.lastName",
  },
];

export const eduData = [
  {
    dType: "edu.degree.ssc",
    dOn: "edu.subject.science",
    dYear: "edu.year.2019",
    dResult: "edu.result.gpassc",
    institution: "edu.institution.bafsj",
    iImage: "/education/bafsj.webp",
    iLogo: "/education/bafsjlogo.webp",
    iDetails: "edu.details.bafsj",
  },
  {
    dType: "edu.degree.hsc",
    dOn: "edu.subject.science",
    dYear: "edu.year.2021",
    dResult: "edu.result.gpahsc",
    institution: "edu.institution.bafsk",
    iImage: "/education/bafsk.webp",
    iLogo: "/education/bafsklogo.webp",
    iDetails: "edu.details.bafsk",
  },
  {
    dType: "edu.degree.bsc",
    dOn: "edu.subject.cse",
    dYear: "edu.year.2026",
    dResult: "edu.result.sgpa",
    institution: "edu.institution.diu",
    iImage: "/education/diu.webp",
    iLogo: "/education/diulogo.webp",
    iDetails: "edu.details.diu",
  },
];

export const projectsInfo = [
  {
    pId: "upgroupasia",
    pTitle: "project.upgroupasia.title",
    pImgSrc: "/projectsss/upasia.webp",
    pType: "project.upgroupasia.type",
    pLevel: "level.expert",
    pLink: "https://golpro.vercel.app/",
    pDetails: "project.upgroupasia.details",
    pMaterials: [
      "html",
      "css",
      "javascriptprogramming",
      "nextjs",
      "mysql",
      "hostinger",
      "vercel",
      "tailwindcss",
    ],
    pCategory: "category.personal",
    pMembers: ["protik0939"],
    pLogo: "/projectsss/logos/upgroup.svg",
  },
  {
    pId: "golpro",
    pTitle: "project.golpro.title",
    pImgSrc: "/projectsss/golpro.webp",
    pType: "project.golpro.type",
    pLevel: "level.expert",
    pLink: "https://golpro.vercel.app/",
    pDetails: "project.golpro.details",
    pMaterials: [
      "html",
      "css",
      "javascriptprogramming",
      "nextjs",
      "nodejs",
      "expressjs",
      "mongodb",
      "vercel",
      "tailwindcss",
    ],
    pCategory: "category.personal",
    pMembers: ["protik0939"],
    pLogo: "/projectsss/logos/golpro.svg",
  },
  {
    pId: "w3university",
    pTitle: "project.w3uni.title",
    pImgSrc: "/projectsss/w3university.webp",
    pType: "project.w3uni.type",
    pLevel: "level.intermediate",
    pLink: "https://protik0939.github.io/W3University/",
    pDetails: "project.w3uni.details",
    pMaterials: ["html", "css", "javascriptprogramming"],
    pCategory: "category.collaborative",
    pMembers: [
      "protik0939",
      "jubairaminsiyum",
      "ishmakrahatrafi",
      "hasanjarif",
      "shakib",
    ],
    pLogo: "/projectsss/logos/W3University.svg",
  },
  {
    pId: "alphaoneeducation",
    pTitle: "project.aoe.title",
    pImgSrc: "/projectsss/alphaone.webp",
    pType: "project.aoe.type",
    pLevel: "level.expert",
    pLink: "https://web.archive.org/web/20250716152154/https://alphaoneedu.com/",
    pDetails: "project.aoe.details",
    pMaterials: [
      "html",
      "css",
      "javascriptprogramming",
      "react",
      "nodejs",
      "expressjs",
      "mongodb",
      "hostinger",
      "vercel",
      "tailwindcss",
    ],
    pCategory: "category.personal",
    pMembers: ["protik0939"],
    pLogo: "/projectsss/logos/alphaoneedu.svg",
  },
  {
    pId: "csepdiu",
    pTitle: "project.cpd.title",
    pImgSrc: "/projectsss/csepdiu.webp",
    pType: "project.cpd.type",
    pLevel: "level.advance",
    pLink: "https://cse-p-diu.web.app/",
    pDetails: "project.cpd.details",
    pMaterials: [
      "html",
      "css",
      "javascriptprogramming",
      "react",
      "nodejs",
      "expressjs",
      "firebase",
      "mongodb",
      "vercel",
      "tailwindcss",
    ],
    pCategory: "category.personal",
    pMembers: ["protik0939"],
    pLogo: "/projectsss/logos/csepdiu.svg",
  },
  {
    pId: "fcpredators",
    pTitle: "project.fcp.title",
    pImgSrc: "/projectsss/fcpredators.webp",
    pType: "project.fcp.type",
    pLevel: "level.advance",
    pLink: "https://fcpredators.web.app/",
    pDetails: "project.fcp.details",
    pMaterials: [
      "html",
      "css",
      "javascriptprogramming",
      "react",
      "firebase",
      "tailwindcss",
    ],
    pCategory: "category.personal",
    pMembers: ["protik0939"],
    pLogo: "/projectsss/logos/fcplogo.svg",
  },
  {
    pId: "batterylowinteractiveclone",
    pTitle: "project.bli.title",
    pImgSrc: "/projectsss/batterylowclone.webp",
    pType: "project.bli.type",
    pLevel: "level.intermediate",
    pLink: "https://batterylowinteractiveclone.netlify.app/",
    pDetails: "project.bli.details",
    pMaterials: [
      "html",
      "css",
      "javascriptprogramming",
      "react",
      "tailwindcss",
      "netlify",
    ],
    pCategory: "category.personal",
    pMembers: ["protik0939"],
    pLogo: "/projectsss/logos/blilogo.png",
  },
  {
    pId: "studentinfo",
    pTitle: "project.stdi.title",
    pImgSrc: "/projectsss/stinfo.webp",
    pType: "project.stdi.type",
    pLevel: "level.beginner",
    pLink: "https://students-info-star-unstar.netlify.app/",
    pDetails: "project.stdi.details",
    pMaterials: [
      "html",
      "css",
      "javascriptprogramming",
      "react",
      "tailwindcss",
      "netlify",
    ],
    pCategory: "category.personal",
    pMembers: ["protik0939"],
    pLogo: null,
  },
  {
    pId: "worldtour",
    pTitle: "project.wtour.title",
    pImgSrc: "/projectsss/worldtour.webp",
    pType: "project.wtour.type",
    pLevel: "level.beginner",
    pLink: "https://worlrtourbyprotik.netlify.app",
    pDetails: "project.wtour.details",
    pMaterials: [
      "html",
      "css",
      "javascriptprogramming",
      "react",
      "tailwindcss",
      "netlify",
    ],
    pCategory: "category.personal",
    pMembers: ["protik0939"],
    pLogo: null,
  },
  {
    pId: "weatherupdate",
    pTitle: "project.wupdt.title",
    pImgSrc: "/projectsss/weatherinfo.webp",
    pType: "project.wupdt.type",
    pLevel: "level.beginner",
    pLink: "https://weatherinfoofsomeplaces.netlify.app",
    pDetails: "project.wupdt.details",
    pMaterials: [
      "html",
      "css",
      "javascriptprogramming",
      "react",
      "tailwindcss",
      "netlify",
    ],
    pCategory: "category.personal",
    pMembers: ["protik0939"],
    pLogo: null,
  },
  {
    pId: "portfolio",
    pTitle: "project.prtflo.title",
    pImgSrc: "/projectsss/oldportfolio.webp",
    pType: "project.prtflo.type",
    pLevel: "level.intermediate",
    pLink: "https://protik0939.blogspot.com/",
    pDetails: "project.prtflo.details",
    pMaterials: ["html", "css", "javascriptprogramming", "blogger"],
    pCategory: "category.personal",
    pMembers: ["protik0939"],
    pLogo: "/projectsss/logos/protik0939.png",
  },
  {
    pId: "golprobd",
    pTitle: "project.golprobd.title",
    pImgSrc: "/projectsss/golprobd.webp",
    pType: "project.golprobd.type",
    pLevel: "level.intermediate",
    pLink: "https://golprobd.blogspot.com",
    pDetails: "project.golprobd.details",
    pMaterials: ["html", "css", "javascriptprogramming", "blogger"],
    pCategory: "category.personal",
    pMembers: ["protik0939"],
    pLogo: "/projectsss/logos/golproLogoSvg.svg",
  },
  {
    pId: "csepdiuold",
    pTitle: "project.cpdold.title",
    pImgSrc: "/projectsss/csepdiuold.webp",
    pType: "project.cpdold.type",
    pLevel: "level.intermediate",
    pLink: "https://csepdiu.blogspot.com/",
    pDetails: "project.cpdold.details",
    pMaterials: ["html", "css", "javascriptprogramming", "blogger"],
    pCategory: "category.personal",
    pMembers: ["protik0939"],
    pLogo: "/projectsss/logos/csepdiu.svg",
  },
  {
    pId: "fcpredatorsold",
    pTitle: "project.fcpold.title",
    pImgSrc: "/projectsss/fcpredatorsold.webp",
    pType: "project.fcpold.type",
    pLevel: "level.intermediate",
    pLink: "https://fc-predators.blogspot.com/",
    pDetails: "project.fcpold.details",
    pMaterials: ["html", "css", "javascriptprogramming", "blogger"],
    pCategory: "category.personal",
    pMembers: ["protik0939"],
    pLogo: "/projectsss/logos/fcplogo.svg",
  },
  {
    pId: "abcbank",
    pTitle: "project.abcbank.title",
    pImgSrc: "/projectsss/abcbank.webp",
    pType: "project.abcbank.type",
    pLevel: "level.novice",
    pLink: "https://protik0939.github.io/ABC-Bank/",
    pDetails: "project.abcbank.details",
    pMaterials: ["html", "css", "javascriptprogramming"],
    pCategory: "category.personal",
    pMembers: ["protik0939"],
    pLogo: null,
  },
];

export const skillData = [
  {
    id: "pl1",
    title: "skills.programmingLanguages",
    sdInfos: [
      {
        id: "cprogramming",
        name: "skills.c.name",
        logo: "/langlogo/c.webp",
        percentage: "97",
        percentageForTxt: "skills.c.percentage",
      },
      {
        id: "cppprogramming",
        name: "skills.cpp.name",
        logo: "/langlogo/cpp.webp",
        percentage: "98",
        percentageForTxt: "skills.cpp.percentage",
      },
      {
        id: "javaprogramming",
        name: "skills.java.name",
        logo: "/langlogo/java.webp",
        percentage: "40",
        percentageForTxt: "skills.java.percentage",
      },
      {
        id: "javascriptprogramming",
        name: "skills.javascript.name",
        logo: "/langlogo/javascript.webp",
        percentage: "90",
        percentageForTxt: "skills.javascript.percentage",
      },
      {
        id: "pythonprogramming",
        name: "skills.python.name",
        logo: "/langlogo/python.webp",
        percentage: "80",
        percentageForTxt: "skills.python.percentage",
      },
      {
        id: "php",
        name: "skills.php.name",
        logo: "/langlogo/php.webp",
        percentage: "70",
        percentageForTxt: "skills.php.percentage",
      },
      {
        id: "dart",
        name: "skills.dart.name",
        logo: "/langlogo/dart.webp",
        percentage: "50",
        percentageForTxt: "skills.dart.percentage",
      },
    ],
  },
  {
    id: "msl2",
    title: "skills.markupStyling",
    sdInfos: [
      {
        id: "html",
        name: "skills.html.name",
        logo: "/langlogo/html.webp",
        percentage: "99",
        percentageForTxt: "skills.html.percentage",
      },
      {
        id: "css",
        name: "skills.css.name",
        logo: "/langlogo/css.webp",
        percentage: "95",
        percentageForTxt: "skills.css.percentage",
      },
    ],
  },
  {
    id: "dtbs3",
    title: "skills.databases",
    sdInfos: [
      {
        id: "mysql",
        name: "skills.mysql.name",
        logo: "/langlogo/mysql.webp",
        percentage: "78",
        percentageForTxt: "skills.mysql.percentage",
      },
      {
        id: "mongodb",
        name: "skills.mongodb.name",
        logo: "/langlogo/mongodb.webp",
        percentage: "84",
        percentageForTxt: "skills.mongodb.percentage",
      },
    ],
  },
  {
    id: "lbrsfrms4",
    title: "skills.librariesFrameworks",
    sdInfos: [
      {
        id: "react",
        name: "skills.react.name",
        logo: "/langlogo/react.webp",
        percentage: "88",
        percentageForTxt: "skills.react.percentage",
      },
      {
        id: "nodejs",
        name: "skills.nodejs.name",
        logo: "/langlogo/nodejs.webp",
        percentage: "77",
        percentageForTxt: "skills.nodejs.percentage",
      },
      {
        id: "expressjs",
        name: "skills.expressjs.name",
        logo: "/langlogo/expressjs.webp",
        percentage: "60",
        percentageForTxt: "skills.expressjs.percentage",
      },
      {
        id: "tailwindcss",
        name: "skills.tailwindcss.name",
        logo: "/langlogo/tailwindcss.webp",
        percentage: "90",
        percentageForTxt: "skills.tailwindcss.percentage",
      },
      {
        id: "nextjs",
        name: "skills.nextjs.name",
        logo: "/langlogo/nextjs.webp",
        percentage: "80",
        percentageForTxt: "skills.nextjs.percentage",
      },
      {
        id: "laravel",
        name: "skills.laravel.name",
        logo: "/langlogo/laravel.webp",
        percentage: "65",
        percentageForTxt: "skills.laravel.percentage",
      },
      {
        id: "flutter",
        name: "skills.flutter.name",
        logo: "/langlogo/flutter.webp",
        percentage: "30",
        percentageForTxt: "skills.flutter.percentage",
      },
    ],
  },
  {
    id: "tcnolgy5",
    title: "skills.technologies",
    sdInfos: [
      {
        id: "pwa",
        name: "skills.pwa.name",
        logo: "/langlogo/pwa.webp",
        percentage: "80",
        percentageForTxt: "skills.pwa.percentage",
      },
      {
        id: "jwt",
        name: "skills.jwt.name",
        logo: "/langlogo/jwt.webp",
        percentage: "85",
        percentageForTxt: "skills.jwt.percentage",
      },
      {
        id: "axios",
        name: "skills.axios.name",
        logo: "/langlogo/axios.webp",
        percentage: "87",
        percentageForTxt: "skills.axios.percentage",
      },
    ],
  },
  {
    id: "platforms6",
    title: "skills.platforms",
    sdInfos: [
      {
        id: "blogger",
        name: "skills.blogger.name",
        logo: "/langlogo/blogger.webp",
        percentage: "99",
        percentageForTxt: "skills.blogger.percentage",
      },
      {
        id: "firebase",
        name: "skills.firebase.name",
        logo: "/langlogo/fireBase.webp",
        percentage: "70",
        percentageForTxt: "skills.firebase.percentage",
      },
      {
        id: "vercel",
        name: "skills.vercel.name",
        logo: "/langlogo/vercel.webp",
        percentage: "70",
        percentageForTxt: "skills.vercel.percentage",
      },
      {
        id: "hostinger",
        name: "skills.hostinger.name",
        logo: "/langlogo/hostinger.webp",
        percentage: "40",
        percentageForTxt: "skills.hostinger.percentage",
      },
      {
        id: "netlify",
        name: "skills.netlify.name",
        logo: "/langlogo/netlify.webp",
        percentage: "80",
        percentageForTxt: "skills.netlify.percentage",
      },
    ],
  },
  {
    id: "tools7",
    title: "skills.tools",
    sdInfos: [
      {
        id: "gitgithub",
        name: "skills.gitgithub.name",
        logo: "/langlogo/gitgithub.webp",
        percentage: "95",
        percentageForTxt: "skills.gitgithub.percentage",
      },
      {
        id: "visualstudiocode",
        name: "skills.visualstudiocode.name",
        logo: "/langlogo/vscode.webp",
        percentage: "99",
        percentageForTxt: "skills.visualstudiocode.percentage",
      },
      {
        id: "xampp",
        name: "skills.xampp.name",
        logo: "/langlogo/xampp.webp",
        percentage: "85",
        percentageForTxt: "skills.xampp.percentage",
      },
      {
        id: "laragon",
        name: "skills.laragon.name",
        logo: "/langlogo/laragon.webp",
        percentage: "90",
        percentageForTxt: "skills.laragon.percentage",
      },
      {
        id: "postman",
        name: "skills.postman.name",
        logo: "/langlogo/postman.webp",
        percentage: "60",
        percentageForTxt: "skills.postman.percentage",
      },
      {
        id: "docker",
        name: "skills.docker.name",
        logo: "/langlogo/docker.webp",
        percentage: "20",
        percentageForTxt: "skills.docker.percentage",
      },
    ],
  },
  {
    id: "others8",
    title: "skills.others",
    sdInfos: [
      {
        id: "figma",
        name: "skills.figma.name",
        logo: "/langlogo/others/figma.webp",
        percentage: "80",
        percentageForTxt: "skills.figma.percentage",
      },
      {
        id: "adobephotoshop",
        name: "skills.adobephotoshop.name",
        logo: "/langlogo/others/photoshop.webp",
        percentage: "95",
        percentageForTxt: "skills.adobephotoshop.percentage",
      },
      {
        id: "adobepremierepro",
        name: "skills.adobepremierepro.name",
        logo: "/langlogo/others/premierepro.webp",
        percentage: "90",
        percentageForTxt: "skills.adobepremierepro.percentage",
      },
      {
        id: "adobeaudition",
        name: "skills.adobeaudition.name",
        logo: "/langlogo/others/audition.webp",
        percentage: "93",
        percentageForTxt: "skills.adobeaudition.percentage",
      },
      {
        id: "adobeillustrator",
        name: "skills.adobeillustrator.name",
        logo: "/langlogo/others/illustrator.webp",
        percentage: "75",
        percentageForTxt: "skills.adobeillustrator.percentage",
      },
      {
        id: "adobeaftereffects",
        name: "skills.adobeaftereffects.name",
        logo: "/langlogo/others/aftereffects.webp",
        percentage: "40",
        percentageForTxt: "skills.adobeaftereffects.percentage",
      },
      {
        id: "msword",
        name: "skills.msword.name",
        logo: "/langlogo/others/msword.webp",
        percentage: "90",
        percentageForTxt: "skills.msword.percentage",
      },
      {
        id: "mspowerpoint",
        name: "skills.mspowerpoint.name",
        logo: "/langlogo/others/mspowerpoint.webp",
        percentage: "97",
        percentageForTxt: "skills.mspowerpoint.percentage",
      },
      {
        id: "googledocs",
        name: "skills.googledocs.name",
        logo: "/langlogo/others/googledocs.webp",
        percentage: "99",
        percentageForTxt: "skills.googledocs.percentage",
      },
      {
        id: "googleforms",
        name: "skills.googleforms.name",
        logo: "/langlogo/others/googleforms.webp",
        percentage: "99",
        percentageForTxt: "skills.googleforms.percentage",
      },
      {
        id: "googlesheets",
        name: "skills.googlesheets.name",
        logo: "/langlogo/others/googlesheets.webp",
        percentage: "99",
        percentageForTxt: "skills.googlesheets.percentage",
      },
      {
        id: "googlesites",
        name: "skills.googlesites.name",
        logo: "/langlogo/others/googlesites.webp",
        percentage: "80",
        percentageForTxt: "skills.googlesites.percentage",
      },
      {
        id: "googleslides",
        name: "skills.googleslides.name",
        logo: "/langlogo/others/googleslides.webp",
        percentage: "90",
        percentageForTxt: "skills.googleslides.percentage",
      },
      {
        id: "filmora",
        name: "skills.filmora.name",
        logo: "/langlogo/others/filmora.webp",
        percentage: "95",
        percentageForTxt: "skills.filmora.percentage",
      },
    ],
  },
];

export const teamInfo = [
  {
    tId: "protik0939",
    tName: "teaminfo.protik",
    tImage: "/teamMatesImages/sadatalamprotik.webp",
    prtlink: "https://protik0939.vercel.app",
  },
  {
    tId: "jubairaminsiyum",
    tName: "teaminfo.siyum",
    tImage: "/teamMatesImages/jubairaminsiyum.webp",
    prtlink: "https://www.jubairamin.me/",
  },
  {
    tId: "ishmakrahatrafi",
    tName: "teaminfo.rafi",
    tImage: "/teamMatesImages/ishmakrahatrafi.webp",
    prtlink: "https://rahatrafi11.blogspot.com/",
  },
  {
    tId: "hasanjarif",
    tName: "teaminfo.jarif",
    tImage: "/teamMatesImages/hasanjarif.webp",
    prtlink: "https://jarif12538.github.io/",
  },
  {
    tId: "shakib",
    tName: "teaminfo.shakib",
    tImage: "/teamMatesImages/shakib.webp",
    prtlink: "https://sites.google.com/diu.edu.bd/musfiqur-shakib/?pli=1",
  },
];

export const blogPost = [
  {
    _id: "medibot-Smart-Line-Following-Medicine-Delivery-Robot",
    title: "blogs.medibot.title",
    author: "teaminfo.protik",
    uploadTime: "2025-06-06T13:45:00Z",
    timeToRead: "blogs.medibot.timeToRead",
    fullDetails: "blogs.medibot.fulldetails",
    tags: [
        "robotics",
        "arduino",
        "medicine delivery",
        "line following robot",
        "medibot",
        "conference paper",
    ],
    imageSource: "/posts/medibot.webp",
  },
  {
    _id: "my-journey-in-phitron-and-problem-solving",
    title: "blogs.myjourneyinphitron.title",
    author: "teaminfo.protik",
    uploadTime: "2023-09-01T17:25:00Z",
    timeToRead: "blogs.myjourneyinphitron.timeToRead",
    fullDetails: "blogs.myjourneyinphitron.fulldetails",
    tags: [
      "problemsolving",
      "programming",
      "phitron",
      "journey",
      "codeforces",
      "codechef",
    ],
    imageSource: "/posts/codeforcescodechef.webp",
  },
];
