

export const topBarData = [
    {
        first: 'Hello!',
        second: 'I am',
        third: 'Sadat Alam',
        fourth: 'Protik',
    }
];

export const eduData = [
    {
        dType: 'SSC',
        dOn: 'Science',
        dYear: '2019',
        dResult: 'GPA-4.67',
        institution: 'BAF Shaheen College, Jashore',
        iImage: '/education/bafsj.webp',
        iLogo: '/education/bafsjlogo.webp',
        iDetails: "BAF Shaheen College Jashore is a well-known educational institution located in Jashore, Bangladesh, under the supervision of the Bangladesh Air Force. Established with the aim of providing high-quality education to students from diverse backgrounds, the college offers a curriculum that balances academic excellence with discipline and moral values. It serves both boys and girls, offering education from the primary to higher secondary levels. The college is renowned for its strong emphasis on discipline, co-curricular activities, and producing well-rounded students prepared for higher education and leadership roles.",
    },
    {
        dType: 'HSC',
        dOn: 'Science',
        dYear: '2021',
        dResult: 'GPA-5.00',
        institution: 'BAF Shaheen College, Kurmitola',
        iImage: '/education/bafsk.webp',
        iLogo: '/education/bafsklogo.webp',
        iDetails: "BAF Shaheen College Kurmitola, situated in Dhaka Cantonment, is a prominent educational institution run under the administration of the Bangladesh Air Force. Established with the vision of fostering academic excellence alongside moral and ethical development, the college offers education from the primary level up to higher secondary. Known for its disciplined environment and high academic standards, the institution provides a balanced curriculum that includes both curricular and extracurricular activities. BAF Shaheen College Kurmitola has a reputation for nurturing leadership, discipline, and creativity in students, preparing them for success in higher education and future endeavors.",
    },
    {
        dType: 'BSc',
        dOn: 'CSE',
        dYear: '2026',
        dResult: 'SGPA-3.69',
        institution: 'Daffodil International University',
        iImage: '/education/diu.webp',
        iLogo: '/education/diulogo.webp',
        iDetails: "Daffodil International University (DIU) is one of the leading private universities in Bangladesh, known for its innovative approach to education and emphasis on modern technology and research. Established in 2002, DIU offers a wide range of undergraduate and postgraduate programs in fields such as engineering, business, computer science, humanities, and social sciences. The university places a strong focus on quality education, global exposure, and practical skills development, preparing students for the competitive global job market. With state-of-the-art facilities, a vibrant campus life, and numerous international partnerships, DIU has earned a reputation for fostering creativity, entrepreneurship, and academic excellence.",
    }
];


export const projectsInfo = [
    {
        pId: 'alphaoneeducation',
        pTitle: 'Alphaone Education Consultancy',
        pImgSrc: '/projectsss/alphaone.webp',
        pType: 'Instution Website',
        pLevel: 'Expert',
        pLink: 'https://alphaoneedu.com/',
        pDetails: 'This project is made for Alphaone Education Consultancy where users can see about them and can apply for their consultancy.',
        pMaterials: ['Html', 'CSS', 'Javascript', 'React', 'Node JS', 'Express JS', 'Firebase', 'MongoDB', 'Hostinger', 'Vercel', 'TailwindCSS'],
    },
    {
        pId: 'csepdiu',
        pTitle: 'CSE P DIU',
        pImgSrc: '/projectsss/csepdiu.webp',
        pType: 'Student Social Media',
        pLevel: 'Advance',
        pLink: 'https://cse-p-diu.web.app/',
        pDetails: 'This project is a Social media and others online tools for studenta platforms that I made for my university section. Only students/teachers of our university can login here.',
        pMaterials: ['Html', 'CSS', 'Javascript', 'React', 'Node JS', 'Express JS', 'Firebase', 'MongoDB', 'Vercel', 'TailwindCSS'],
    },
    {
        pId: 'fcpredators',
        pTitle: 'FC Predators',
        pImgSrc: '/projectsss/fcpredators.webp',
        pType: 'Football Club Portal',
        pLevel: 'Advance',
        pLink: 'https://fcpredators.web.app/',
        pDetails: 'This project is a Portal on my childhood friends with whom we used to play football and created a club named FC Predators. I spent the best times of my life with them!',
        pMaterials: ['Html', 'CSS', 'Javascript', 'React', 'Firebase', 'TailwindCSS'],
    },
    {
        pId: 'batterylowinteractiveclone',
        pTitle: 'Battery Low Interactive Clone',
        pImgSrc: '/projectsss/batterylowclone.webp',
        pType: "A Tech Company Website's clone",
        pLevel: 'Intermediate',
        pLink: 'https://batterylowinteractiveclone.netlify.app/',
        pDetails: "In the beginning of my react development journey, I made a clone of a popular Bangladeshi Tech Company, Battery Low Interactive's Clone",
        pMaterials: ['Html', 'CSS', 'Javascript', 'React', 'TailwindCSS'],
    },
    {
        pId: 'studentinfo',
        pTitle: 'Students Info',
        pImgSrc: '/projectsss/stinfo.webp',
        pType: "Student Star Marking",
        pLevel: 'Beginner',
        pLink: 'https://students-info-star-unstar.netlify.app/',
        pDetails: "This is just a basic website marking students as star and unstar nothing else",
        pMaterials: ['Html', 'CSS', 'Javascript', 'React', 'TailwindCSS'],
    },
    {
        pId: 'worldtour',
        pTitle: 'World Tour',
        pImgSrc: '/projectsss/worldtour.webp',
        pType: "World's All Country Info",
        pLevel: 'Beginner',
        pLink: 'https://worlrtourbyprotik.netlify.app',
        pDetails: "An website to show information of all the countries accross world. Some other functionalities are also there but not much well organized. Used Rest API for country data",
        pMaterials: ['Html', 'CSS', 'Javascript', 'React', 'TailwindCSS'],
    },
    {
        pId: 'weatherupdate',
        pTitle: 'Live Weather Update',
        pImgSrc: '/projectsss/weatherinfo.webp',
        pType: "Life Weather Update",
        pLevel: 'Beginner',
        pLink: 'https://weatherinfoofsomeplaces.netlify.app',
        pDetails: "Here some country's weather info will be shown live and we can switch between places. It's a very basic project which I made in the begining of my React Framework learning journey.",
        pMaterials: ['Html', 'CSS', 'Javascript', 'React', 'TailwindCSS'],
    },
    {
        pId: 'portfolio',
        pTitle: 'My Old Portfolio',
        pImgSrc: '/projectsss/oldportfolio.webp',
        pType: "Portfolio",
        pLevel: 'Intermediate',
        pLink: 'https://protik0939.blogspot.com/',
        pDetails: "This one is my first portfolio made using plain html css javascript on Blogger.",
        pMaterials: ['Html', 'CSS', 'Javascript', 'Blogger'],
    },
    {
        pId: 'golprobd',
        pTitle: 'GolProBD',
        pImgSrc: '/projectsss/golprobd.webp',
        pType: "An online Magazine",
        pLevel: 'Intermediate',
        pLink: 'https://golprobd.blogspot.com',
        pDetails: "Feeling boared? Read stories and other contents by me on my online Magazine type OTT. It's one of my starting project of HTML CSS Journey.",
        pMaterials: ['Html', 'CSS', 'Javascript', 'Blogger'],
    },
    {
        pId: 'csepdiuold',
        pTitle: 'CSE P DIU (Old)',
        pImgSrc: '/projectsss/csepdiuold.webp',
        pType: 'Student Social Media',
        pLevel: 'Intermediate',
        pLink: 'https://csepdiu.blogspot.com/',
        pDetails: '(Its the old version of above CSE P DIU) This project is a Social media and others online tools for studenta platforms that I made for my university section. Only students/teachers of our university can login here.',
        pMaterials: ['Html', 'CSS', 'Javascript', 'Blogger'],
    },
    {
        pId: 'fcpredatorsold',
        pTitle: 'FC Predators (Old)',
        pImgSrc: '/projectsss/fcpredatorsold.webp',
        pType: 'Football Club Portal',
        pLevel: 'Intermediate',
        pLink: 'https://fc-predators.blogspot.com/',
        pDetails: '(Its the old version of above FC Predators) This project is a Portal on my childhood friends with whom we used to play football and created a club named FC Predators. I spent the best times of my life with them!',
        pMaterials: ['Html', 'CSS', 'Javascript', 'Blogger'],
    },
    {
        pId: 'abcbank',
        pTitle: 'ABC Bank',
        pImgSrc: '/projectsss/abcbank.webp',
        pType: 'Personal Bank',
        pLevel: 'Novice',
        pLink: 'https://protik0939.github.io/ABC-Bank/',
        pDetails: "This one is so basic project when I've learnt Javascriptly deeply. Oh one think, here user protik0939@gmail.com and pass 12345",
        pMaterials: ['Html', 'CSS', 'Javascript'],
    },
]

export const skillData = [
    {
        id: 'pl1',
        title: 'Programming Languages',
        sdInfos: [
            {
                id: 'cprogramming',
                name: 'C',
                logo: '/langlogo/c.webp',
                percentage: '100%',
            },
            {
                id: 'cppprogramming',
                name: 'C++',
                logo: '/langlogo/cpp.webp',
                percentage: '100%',
            },
            {
                id: 'javaprogramming',
                name: 'Java',
                logo: '/langlogo/java.webp',
                percentage: '100%',
            },
            {
                id: 'javascriptprogramming',
                name: 'JavaScript',
                logo: '/langlogo/javascript.webp',
                percentage: '100%',
            },
            {
                id: 'pythonprogramming',
                name: 'Python',
                logo: '/langlogo/python.webp',
                percentage: '100%',
            },
        ],
    },
    {
        id: 'msl2',
        title: 'Markup/Styling Languages',
        sdInfos: [
            {
                id: 'html',
                name: 'HTML',
                logo: '/langlogo/html.webp',
                percentage: '100%',
            },
            {
                id: 'css',
                name: 'CSS',
                logo: '/langlogo/css.webp',
                percentage: '100%',
            },
        ],
    },
    {
        id: 'dtbs3',
        title: 'Databases',
        sdInfos: [
            {
                id: 'mysql',
                name: 'MySql',
                logo: '/langlogo/mysql.webp',
                percentage: '100%',
            },
            {
                id: 'mongodb',
                name: 'MongoDB',
                logo: '/langlogo/mongodb.webp',
                percentage: '100%',
            },
        ],
    },
    {
        id: 'lbrsfrms4',
        title: 'Libraries/Frameworks',
        sdInfos: [
            {
                id: 'react',
                name: 'React',
                logo: '/langlogo/react.webp',
                percentage: '100%',
            },
            {
                id: 'nodejs',
                name: 'Node JS',
                logo: '/langlogo/nodejs.webp',
                percentage: '100%',
            },
            {
                id: 'Express JS',
                name: 'MySql',
                logo: '/langlogo/expressjs.webp',
                percentage: '100%',
            },
            {
                id: 'Tailwind CSS',
                name: 'MySql',
                logo: '/langlogo/tailwindcss.webp',
                percentage: '100%',
            },
            {
                id: 'Next JS',
                name: 'MySql',
                logo: '/langlogo/nextjs.webp',
                percentage: '100%',
            },
        ],
    },
    {
        id: 'tcnolgy5',
        title: 'Technologies',
        sdInfos: [
            {
                id: 'pwa',
                name: 'PWA',
                logo: '/langlogo/pwa.webp',
                percentage: '100%',
            },
            {
                id: 'jwt',
                name: 'JWT',
                logo: '/langlogo/jwt.webp',
                percentage: '100%',
            },
            {
                id: 'axios',
                name: 'Axios',
                logo: '/langlogo/axios.webp',
                percentage: '100%',
            },
        ],
    },
    {
        id: 'platforms6',
        title: 'Platforms',
        sdInfos: [
            {
                id: 'blogger',
                name: 'Blogger',
                logo: '/langlogo/blogger.webp',
                percentage: '100%',
            },
            {
                id: 'firebase',
                name: 'Firebase',
                logo: '/langlogo/fireBase.webp',
                percentage: '100%',
            },
            {
                id: 'Vercel',
                name: 'MongoDB',
                logo: '/langlogo/vercel.webp',
                percentage: '100%',
            },
        ],
    },
    {
        id: 'others7',
        title: 'Others',
        sdInfos: [
            {
                id: 'figma',
                name: 'Figma',
                logo: '/langlogo/others/figma.webp',
                percentage: '100%',
            },
            {
                id: 'adobephotoshop',
                name: 'Adobe Photoshop',
                logo: '/langlogo/others/photoshop.webp',
                percentage: '100%',
            },
            {
                id: 'adobepremierepro',
                name: 'Adobe Premiere Pro',
                logo: '/langlogo/others/premierepro.webp',
                percentage: '100%',
            },
            {
                id: 'adobeaudition',
                name: 'Adobe Audition',
                logo: '/langlogo/others/audition.webp',
                percentage: '100%',
            },
            {
                id: 'adobeillustrator',
                name: 'Adobe Illustrator',
                logo: '/langlogo/others/illustrator.webp',
                percentage: '100%',
            },
            {
                id: 'adobeaftereffects',
                name: 'Adobe After Effects',
                logo: '/langlogo/others/aftereffects.webp',
                percentage: '100%',
            },
            {
                id: 'msword',
                name: 'MS Word',
                logo: '/langlogo/others/msword.webp',
                percentage: '100%',
            },
            {
                id: 'mspowerpoint',
                name: 'MS PowerPoint',
                logo: '/langlogo/others/mspowerpoint.webp',
                percentage: '100%',
            },
            {
                id: 'googledocs',
                name: 'Google Docs',
                logo: '/langlogo/others/googledocs.webp',
                percentage: '100%',
            },
            {
                id: 'googleforms',
                name: 'Google Forms',
                logo: '/langlogo/others/googleforms.webp',
                percentage: '100%',
            },
            {
                id: 'googlesheets',
                name: 'Google Sheets',
                logo: '/langlogo/others/googlesheets.webp',
                percentage: '100%',
            },
            {
                id: 'googlesites',
                name: 'Google Sites',
                logo: '/langlogo/others/googlesites.webp',
                percentage: '100%',
            },
            {
                id: 'googleslides',
                name: 'Google Slides',
                logo: '/langlogo/others/googleslides.webp',
                percentage: '100%',
            },
            {
                id: 'filmora',
                name: 'Filmora',
                logo: '/langlogo/others/filmora.webp',
                percentage: '100%',
            },
        ],
    },
]